"""
Light, sky, fog, clouds and rain as BeamNG environment objects.

Instead of guessed values, all fields come from BeamNG's own defaults (data/environment_defaults.json, generated by
tools/extract_environment_defaults.py): a tuned set from the italy level plus the color/light values of the
"sunny_noon" weather preset. BeamNG computes the sun position itself from TimeOfDay (date, latitude/longitude, time
of day); as in the original levels, there is no separate Sun object (the ScatterSky provides the sun).

This makes the time of day, clouds and the weather presets (art/weather/*.json) work in the game, since they act
through exactly these object classes (lua/ge/extensions/core/environment.lua, weather.lua).
"""

import copy
import json
import re
import uuid
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

DEFAULTS_PATH = Path(__file__).parent.parent.parent / "data" / "environment_defaults.json"
CLOUD_TEXTURE = "art/skies/clouds/clouds_normal_displacement.png"  # global asset in gameengine.zip

# Fixed IDs of the two objects that already existed earlier (stable across exports)
_FIXED_IDS = {
    "LevelInfo": "64e00688-24f4-417d-a0c8-25e1e7d59cce",
    "ScatterSky": "f0c7b6f6-7e4a-4b2a-8c4f-5c6f0c2a9c55",
}
_NAMES = {
    "LevelInfo": "theLevelInfo",  # name BeamNG expects (scenetree.theLevelInfo, see bigMapMode.lua)
    "ScatterSky": "the_sky",
    "TimeOfDay": "tod",
    "CloudLayer": "clouds1",
    "Precipitation": "rain_coverage",
}


def load_environment_defaults(path: Optional[Path] = None) -> Dict:
    """Loads data/environment_defaults.json (reference values from the game)."""
    return json.loads(Path(path or DEFAULTS_PATH).read_text(encoding="utf-8"))


def clock_to_time_of_day(clock: str) -> float:
    """
    Time of day "HH:MM" -> value for TimeOfDay.time, using BeamNG's own formula (core/solarTimeOfDay.lua,
    timeFromMinutes): (minutes/1440 - 0.5) mod 1. So 12:00 = 0.0, 18:00 = 0.25, midnight = 0.5, 06:00 = 0.75
    (the italy level starts at 0.92 = 10:05).
    """
    match = re.fullmatch(r"\s*(\d{1,2}):(\d{2})\s*", clock or "")
    if not match:
        raise ValueError(f"Time of day must be HH:MM, was: {clock!r}")
    hours, minutes = int(match.group(1)), int(match.group(2))
    if hours > 24 or minutes > 59 or (hours == 24 and minutes):
        raise ValueError(f"Invalid time of day: {clock!r}")
    return ((hours * 60 + minutes) / 1440.0 - 0.5) % 1.0


def _line(class_name: str, fields: Dict) -> Dict:
    persistent_id = _FIXED_IDS.get(class_name) or str(uuid.uuid5(uuid.NAMESPACE_URL, f"world_to_beamng/environment/{class_name}"))
    line = {"name": _NAMES[class_name], "class": class_name, "persistentId": persistent_id, "parentId": "MissionGroup"}
    line.update(copy.deepcopy(fields))
    return line


def build_environment_lines(
    defaults: Dict,
    latitude: float,
    longitude: float,
    date: Tuple[int, int, int],
    clock: str,
    fog_color: Sequence[float],
    fog_density: float,
    visible_distance: float,
    environment_map: str,
) -> List[Dict]:
    """
    Builds LevelInfo, ScatterSky, TimeOfDay, CloudLayer and Precipitation for main/MissionGroup/items.level.json.

    Args:
        defaults: Result of load_environment_defaults()
        latitude, longitude: Location for the sun position
        date: (year, month, day) for the sun position
        clock: Start time "HH:MM"
        fog_color, fog_density: Haze (set per level, like the original levels)
        visible_distance: View distance in meters
        environment_map: Global environment map for vehicle reflections
    """
    weather = defaults.get("weather", {})
    time_value = clock_to_time_of_day(clock)
    year, month, day = date

    level_info = {
        **defaults["LevelInfo"],
        "gravity": -9.81,
        "levelName": "world_to_beamng",
        "decalsEnabled": True,
        "canSave": True,
        "globalEnviromentMap": environment_map,  # this is how the engine writes it (typo included)
        "visibleDistance": visible_distance,
        "fogDensity": fog_density,
        "fogColor": list(fog_color),
    }
    scatter_sky = {**defaults["ScatterSky"], **weather.get("ScatterSky", {})}
    time_of_day = {
        **defaults["TimeOfDay"],
        "latitude": latitude,
        "longitude": longitude,
        "year": year,
        "month": month,
        "day": day,
        "time": time_value,
        "startTime": time_value,
        "play": False,
    }
    clouds = {**defaults["CloudLayer"], **weather.get("CloudLayer", {}), "texture": CLOUD_TEXTURE, "position": [0, 0, 0]}
    rain = {**defaults["Precipitation"], **weather.get("Precipitation", {}), "position": [0, 0, 0]}

    return [
        _line("LevelInfo", level_info),
        _line("ScatterSky", scatter_sky),
        _line("TimeOfDay", time_of_day),
        _line("CloudLayer", clouds),
        _line("Precipitation", rain),
    ]
